name: Lint

on:
pull_request:
  branches: [ main ]
push:
  branches: [ main ]

jobs:
  flake8-lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 . 
          

