# Tests crapgpt's Python code within a QIIME 2 conda environment.
# Also lints and stylechecks the code.
name: Lint and Testing Check

# On is the trigger. So the workflow runs on push/pull events to the main branch
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  # build is a job
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10" 
      - name: Create conda environment and install flake8
        run: |
          conda create -y -n crapgpt python=3.10
          conda install -n crapgpt -c conda-forge flake8
      - name: Run linting
        run: |
          conda run -n crapgpt flake8 src
