# Tests crapgpt's Python code within a QIIME 2 conda environment.
# Also lints and stylechecks the code.
name: Lint and Testing Check

# On is the trigger. So the workflow runs on push/pull events to the main branch
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  # build is a job
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Set up conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: 3.10
        conda-channels: anaconda, conda-forge
    

    - name: Create conda environment
      run: |
        conda create -y -n crapgpt python=3.10 flake8
    # - name: Install crapgpt
    #  run: |

    - name: Run linting and stylechecking
      run: |
        conda activate crapgpt
        flake8 src
    

   # - name: Run tests
   #   run: conda run -n qiime2-dev make test

    

    
